name: DB Migration Caution

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  commenter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # migration に変更が加えられた際に
      - name: Detect migration
        uses: dorny/paths-filter@v2
        id: filter-migration
        with:
          list-files: shell
          filters: |
            sqls:
              - '**/migration/*.sql'

      # 上記のファイルを対象にgrep
      - name: Grep something
        id: grep-suspicious
        run: |
          suspicious_keywords=("drop table" "drop column")
          pattern=$(IFS="|"; echo "${suspicious_keywords[*]}")
          migration_dir="./migration"
          suspicious_sqls=$(find ${migration_dir}/*.sql | xargs grep -li -E "${pattern}" || true)
          echo "::set-output name=suspicious-sqls::$suspicious_sqls"

      - name: Debug2
        run: echo ${{ steps.grep-suspicious.outputs.suspicious-sqls }}

      # コメントがすでに存在しないか確認し
      # - name: Check existing caution comment
      #   uses: peter-evans/find-comment@v1
      #   id: check-migration-comment
      #   with:
      #     issue-number: ${{ github.event.pull_request.number }}
      #     comment-author: 'github-actions[bot]'
      #     body-includes: Contains db migration!

      # コメントを追記
      - name: Write DB migration caution comment
        uses: peter-evans/create-or-update-comment@v1
        if: steps.filter-migration.outputs.sqls == 'true' &&
            steps.check-migration-comment.outputs.comment-id == ''
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Contains db migration!