name: DB Migration Caution

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  commenter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 自動生成されたModelファイルの削除or変更を検知
      # output: model 削除or変更が検知された際に 'true'
      # output: model_files 削除or変更された自動生成ファイルパスのカンマ区切り文字列
      - name: Detect DB migration
        id: detect-db-migration
        uses: dorny/paths-filter@v2
        with:
          list-files: 'shell'
          filters: |
            sql:
              - 'migration/*.sql'

      # migration SQLを対象にキーワードでgrep
      # output: sqls
      # - ヒットした場合はSQLファイルパスのカンマ区切り文字列
      # - 1件もヒットしない場合は 'SUSPICIOUS_SQL_NOT_DETECTED' の文字列
      - name: Grep Suspicious SQL
        id: grep-suspicious
        if: steps.detect-db-migration.outputs.sql == 'true'
        run: |
          suspicious_keywords=("drop table" "drop column")
          pattern=$(IFS="|"; echo "${suspicious_keywords[*]}")
          echo ${{steps.detect-db-migration.outputs.sql_files}}
          suspicious_sqls=$(grep -li -E "${pattern}" ${{steps.detect-db-migration.outputs.sql_files}} || echo 'SUSPICIOUS_SQL_NOT_DETECTED')
          suspicious_sqls="${suspicious_sqls//$'\n'/,}"
          suspicious_sqls="${suspicious_sqls//\.\//}"
          echo "::set-output name=sqls::$suspicious_sqls"

      # 自動生成されたModelファイルの削除or変更を検知
      # output: model 削除or変更が検知された際に 'true'
      # output: model_files 削除or変更された自動生成ファイルパスのカンマ区切り文字列
      - name: Detect Model Change
        id: detect-model-change
        uses: dorny/paths-filter@v2
        with:
          list-files: 'csv'
          filters: |
            model:
              - deleted|modified: '**/model/*.scala'

      # コメントを再度行うかを判断するために、変更ファイルの一覧からmd5を計算
      - name: Calc MD5
        id: calc-md5
        if: steps.detect-db-migration.outputs.sql == 'true' &&
            steps.grep-suspicious.outputs.sqls != 'SUSPICIOUS_SQL_NOT_DETECTED' &&
            steps.detect-model-change.outputs.model == 'true'
        run: |
          md5=(`echo -n "${{steps.grep-suspicious.outputs.sqls}}${{steps.detect-model-change.outputs.model_files}}" | md5sum`)
          echo $md5
          echo "::set-output name=md5::$md5"

      # ファイルに変更がないかをコメント内のMD5の値から確認
      - name: Check MD5
        id: check-md5
        uses: peter-evans/find-comment@v1
        if: steps.detect-db-migration.outputs.sql == 'true' &&
            steps.grep-suspicious.outputs.sqls != 'SUSPICIOUS_SQL_NOT_DETECTED' &&
            steps.detect-model-change.outputs.model == 'true'
        with:
          issue-number: ${{github.event.pull_request.number}}
          comment-author: 'github-actions[bot]'
          body-includes: ${{steps.calc-md5.outputs.md5}}

      # 変更ファイルの情報をmarkdown用にフォーマットする
      # 改行を%0Aとして表現する理由は https://github.community/t/set-output-truncates-multiline-strings/16852/3 を参照。
      # output: suspicious-sql-list markdownにフォーマットしたSQLのファイルパス一覧
      # output: changed-model-list markdownにフォーマットした自動生成モデルファイルパス一覧
      - name: Format Comment Body
        id: format-body
        if: steps.detect-db-migration.outputs.sql == 'true' &&
            steps.grep-suspicious.outputs.sqls != 'SUSPICIOUS_SQL_NOT_DETECTED' &&
            steps.detect-model-change.outputs.model == 'true'
        run: |
          suspicious_sqls=${{steps.grep-suspicious.outputs.sqls}}
          suspicious_sql_list="- ${suspicious_sqls//','/'%0A- '}"
          echo "::set-output name=suspicious-sql-list::$suspicious_sql_list"
          model_files=${{steps.detect-model-change.outputs.model_files}}
          model_file_list="- ${model_files//','/'%0A- '}"
          echo "::set-output name=changed-model-list::$model_file_list"

      # コメントを追記
      - name: Write caution comment
        uses: peter-evans/create-or-update-comment@v1
        if: steps.detect-db-migration.outputs.sql == 'true' &&
            steps.grep-suspicious.outputs.sqls != 'SUSPICIOUS_SQL_NOT_DETECTED' &&
            steps.detect-model-change.outputs.model == 'true' &&
            steps.check-md5.outputs.comment-id == ''
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: |
            ## Caution!
            DB migration & change of auto-generated model is detected in this one PR.

            ### SQLs
            ${{steps.format-body.outputs.suspicious-sql-list}}

            ### Auto Generated Files
            ${{steps.format-body.outputs.changed-model-list}}

            > ${{steps.calc-md5.outputs.md5}}